### ISSUE TITLE
MIssing code!

### ISSUE THREAD

**Issue by codebauer** [RideBeeline/beeline-firmware-build#1]
Hello,
I saw this and got really excited. Does beeline intend to open source their firmware? I hope so!
I searched beeline.co for github/open-source and didn't find anything, so what gives..

P.S. Hope my beeline arrives soon ;o)

**Comment by chetbox** [comment]
Hi @codebauer! Sorry but we have no plans to open source our main code repos. This repo contains the build system we're using to create the firmware that runs on Beeline. We'll be contributing back to the community where we think there's a good opportunity, but if you have ideas of things you'd like to build with Beeline do let us know and we'll see if there's a good way to do some hacking.
